### ISSUE TITLE
Issues 

### ISSUE THREAD

**Issue by serjiokov** [wyrdsister/StateMachine#1]
https://github.com/wyrdsister/StateMachine/blob/e8c9cb76a5141189d17db966146b9aac36402dbc/src/main/java/properties/ApplicationProperties.java#L23

1)  Using printstacktrace is bad practise
https://stackoverflow.com/questions/7469316/why-is-exception-printstacktrace-considered-bad-practice

2) Does "Queue<Object> queue" keep several objects during waiting  execution ? 
The main idea show how principle of blocking queue works.

3) Please provide the tests.

**Comment by wyrdsister** [comment]
I have a question about the second point. 
Yes, it does. The current server saves new data in a queue while it is processing or sending one portion of data. The sender isn't blocked in this situation, but the server doesn't start processing new data.
Do you want that the server needs to block the input stream of data if it starts processing or sending?
If someone puts data into the server when the server doesn't have not waiting state, the sender should be blocked by the server until it will have a waiting state.

**Comment by serjiokov** [comment]
Hi, please skip 1, 2 by saving the time. Please provided the JUnit tests only.

**Comment by wyrdsister** [comment]
Ok.
I've just fixed **1st point**. And I added some tests using JUnit 5 (**3rd point**).

**Comment by wyrdsister** [comment]
Ok.
I've just fixed **1st point**. And I added some tests using JUnit 5 (**3rd point**).

**Comment by serjiokov** [comment]
> Ok.
> I've just fixed **1st point**. And I added some tests using JUnit 5 (**3rd point**).

Pls, add few tests to check queue is not empty and server pricessing
